import { getTool, settingNames, type Catalog, type Package, type Scenario } from '@/lib/catalog';

const periods=['สัปดาห์ที่ 1','สัปดาห์ที่ 2–4','เดือนที่ 2','เดือนที่ 3'];

export function PrintablePlan({catalog,scenario,item}:{catalog:Catalog;scenario:Scenario;item:Package}){
  const groups:[string,string[]][]=[['เครื่องมือหลัก',scenario.primaryIds],['เครื่องมือเสริม',scenario.supportIds],['เครื่องมือวัดผล',scenario.measureIds],['ข้อมูลอ้างอิง',scenario.referenceIds]];
  return <div className="print-document" aria-hidden="true"><article className="print-sheet"><div className="print-top"><div className="print-cover"><h1>ชุดเครื่องมือ<br/>ที่เหมาะสม<br/>กับสถานการณ์</h1><p>แผนทำงานสำหรับพื้นที่ของคุณ</p></div><div className="print-context"><h2>สถานการณ์</h2><p><b>พื้นที่ดำเนินการ</b> {settingNames[scenario.settingCode]}</p><p><b>สิ่งที่ต้องดำเนินการ</b> {item.name}</p><p><b>เป้าหมาย</b> {item.goal}</p><p><b>กลุ่มเป้าหมาย</b> {scenario.audience}</p><p><b>ผู้ดำเนินการ</b> {scenario.role}</p><p><b>การทำงาน</b> {scenario.level}</p></div></div>
    <section className="print-section print-recommendations"><h2>ชุดเครื่องมือที่แนะนำ</h2><div className="print-tool-grid">{groups.filter(([,ids])=>ids.length).map(([title,ids])=><div className="print-tool" key={title}><span className="print-tool-label">{title}</span><ul>{ids.map(id=>{const tool=getTool(catalog,id);return tool?<li key={id}>{tool.name}</li>:null;})}</ul></div>)}</div></section>
    <section className="print-section print-roadmap"><h2>แผนการดำเนินงาน</h2><div className="print-period-grid">{scenario.phases.map((phase,index)=><div className="print-period" key={index}><h3>{periods[index]??`ช่วงที่ ${index+1}`}</h3><p>{phase}</p></div>)}</div></section>
    </article><article className="print-sheet print-appendix"><h2>รายละเอียดประกอบแผน</h2><p className="print-appendix-intro">{item.name} · {scenario.role} · {scenario.audience}</p><div className="print-appendix-columns"><section><h3>เครื่องมือในแผน</h3>{groups.filter(([,ids])=>ids.length).map(([title,ids])=><div className="print-appendix-group" key={title}><h4>{title}</h4><ul>{ids.map(id=>{const tool=getTool(catalog,id);return tool?<li key={id}>{tool.name}</li>:null;})}</ul></div>)}</section><section><h3>ขั้นตอนลงมือทำ</h3><ol>{scenario.steps.map(step=><li key={step.order}><b>{step.when}</b> {step.action}</li>)}</ol>{scenario.referral&&<div className="print-referral"><h4>เมื่ออยากขอความช่วยเหลือ</h4><p>{scenario.referral}</p></div>}</section></div></article></div>;
}
